[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.0",
    "os-sys>=0.9.1",
    "psutil>=7.0.0",
    "trafilatura>=2.0.0",
]
